 const Language={
  logo:'Datum',
  textFull:'100%',
  textTCTitle:'Terms & Conditions',
  textTC1:'You are giving this dapp the right to access your Nickname to create your access to get your Datum Mascot',
  textTC2:'You can manage permissions in My Data',
  textTC3:'Datum will use this information in accordance with our privacy policy and terms of use',
  textTC4:'Note: Your information will not be shared withour your consent',
  textTC5:'I agree to the terms & conditions and the privacy policy. Click here to view',
  textTC6:'I UNDERSTAND',
  textConnected: 'CONNECTED',
  textDatumId: 'Datum ID',
  textEmail: 'Email Address',
  textIndentity:'Your Identity',
  textApps: 'Apps',
  textSignin:'Sign in With Datum',
  textAppsTitle:'Datum Mascot',
  textMascotButton:'MAKE MY MASCOT!',
  textWallet:'Wallet',
  textMe:'Me',
  textAbout1:'What is This?',
  textAbout2:'This app creates and hosts your very own mascot. The Mascot represents you in the net. You can visit and review your Mascot anytime you want. Give this lucky roulette a spin to get your mascot.',
  textAbout3:'What is collected?',
  textAbout4:'Your Nickname',
  textAboutButton:'COUNT ME IN!',
  placeholder:"Enter Your name here",
  cardText1:'Give your Mascot a name (e.g your nickname)',
  cardText2:'NEXT',
  overlayTitle:'Permission to Write',
  overlayText1:"'Datum Mascot' would like to write and have access to the following data:",
  overlayText2:"Permission for the following attributes :",
  overlayText3:"Your nickname",
  overlayText4:"CONTINUE",
  overlayText5:"CANCEL",
  errorMsg:"Your NickName must be letters without special symbols.",
  overlayText6:"FINNISH",
  overlayText7:'Your Mascot!',
  rouletteSpin:'SPIN!',
  finalText1:'App',
  finalText2:'TYPEA'

}

export default Language;
